/// Includes the attributes generated by `rubble-codegen`.
///
/// # Examples
///
/// This will create a private module `attrs` containing the generated code:
///
/// ```ignore
/// include_attributes!(mod attrs);
/// ```
#[macro_export]
macro_rules! include_attributes {
    ($v:vis mod $name:ident) => {
        $v mod $name {
            include!(concat!(env!("OUT_DIR"), "/rubble_codegen.rs"));
        }
    };
}
